version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated-pr"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@biomejs/*"
          - "@vitest/*"
          - "tsx"
          - "typescript"
          - "vitest"
          - "husky"
          - "yaml"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "commander"
          - "chalk"
          - "cli-spinners"
          - "date-fns"
          - "date-fns-tz"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"